import React, { useEffect, useState } from 'react';
import { useParams, useNavigate, useSearchParams } from 'react-router-dom';
import { api } from '../services/api';
import { motion } from 'motion/react';
import { Loader2, AlertCircle, QrCode } from 'lucide-react';
import { useAuth } from '../context/AuthContext';

export const QRResolverPage: React.FC = () => {
  const { qrId } = useParams<{ qrId: string }>();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const { user, isAuthReady } = useAuth();
  const [status, setStatus] = useState<'loading' | 'error' | 'unlinked'>('loading');
  const [message, setMessage] = useState('');

  useEffect(() => {
    const resolveQR = async () => {
      if (!qrId || !isAuthReady) return;

      const isInternal = searchParams.get('internal') === 'true';
      const sourceQuery = `source=qr${isInternal ? '&internal=true' : ''}`;

      console.log('Resolving QR:', qrId, 'Internal:', isInternal);
      try {
        const qrData = await api.getQRData(qrId);
        console.log('QR Data:', qrData);
        
        if (!qrData) {
          setStatus('error');
          setMessage('Invalid QR Code. This code was not generated by ToLetBro.');
          return;
        }

        if (qrData.status === 'UNLINKED') {
          console.log('QR is UNLINKED');
          // Check if user is logged in as owner
          if (user && user.role === 'OWNER') {
            navigate(`/link-qr/${qrId}`, { replace: true });
          } else {
            setStatus('unlinked');
          }
          return;
        }

        if (qrData.status === 'LINKED' && qrData.ownerId) {
          console.log('QR is LINKED to owner:', qrData.ownerId);
          const properties = await api.getPropertiesByOwnerId(qrData.ownerId);
          console.log('Found properties:', properties.length);
          
          if (properties.length === 1) {
            // Only one property, direct to details
            const p = properties[0];
            const slug = p.slug || p.title
              .toLowerCase()
              .replace(/[^a-z0-9]+/g, '-')
              .replace(/(^-|-$)/g, '');
            setMessage('Redirecting to property details...');
            navigate(`/property/${slug}-${p.id}?${sourceQuery}`, { replace: true });
          } else {
            // Multiple properties or zero, show list
            navigate(`/owner-properties/${qrData.ownerId}?${sourceQuery}`, { replace: true });
          }
        } else {
          console.log('QR is LINKED but ownerId is missing');
          setStatus('error');
          setMessage('This QR code is linked but owner information is missing.');
        }
      } catch (error) {
        console.error('QR Resolution Error:', error);
        setStatus('error');
        setMessage('An error occurred while resolving the QR code.');
      }
    };

    resolveQR();
  }, [qrId, navigate, user, isAuthReady]);

  if (status === 'loading') {
    return (
      <div className="flex h-[80vh] flex-col items-center justify-center text-center px-6">
        <motion.div
          animate={{ rotate: 360 }}
          transition={{ duration: 2, repeat: Infinity, ease: "linear" }}
          className="mb-6 text-brand"
        >
          <Loader2 size={48} />
        </motion.div>
        <h2 className="text-2xl font-bold text-[var(--text-primary)]">{message || 'Resolving QR Code...'}</h2>
        <p className="mt-2 text-[var(--text-secondary)]">{message ? 'Just a moment while we take you there.' : 'Please wait while we find the property details.'}</p>
      </div>
    );
  }

  if (status === 'error') {
    return (
      <div className="flex min-h-[80vh] flex-col items-center justify-center text-center px-6 py-12">
        <div className="mb-6 flex h-24 w-24 items-center justify-center rounded-3xl bg-red-500/10 text-red-500 border border-red-500/20">
          <AlertCircle size={48} />
        </div>
        <h2 className="text-3xl font-bold text-[var(--text-primary)]">Invalid QR Code</h2>
        <p className="mt-4 text-[var(--text-secondary)] max-w-md mx-auto leading-relaxed">
          {message || 'This QR code was not recognized by our system. Please ensure you are scanning an official ToLetBro Smart Board.'}
        </p>
        <div className="mt-10 flex flex-col sm:flex-row gap-4 w-full max-w-xs sm:max-w-md">
          <button 
            onClick={() => navigate('/')}
            className="flex-1 rounded-2xl bg-brand px-8 py-4 font-bold text-black transition-all hover:scale-105 shadow-lg shadow-brand/20"
          >
            Go to Home
          </button>
          <button 
            onClick={() => window.location.reload()}
            className="flex-1 rounded-2xl border border-[var(--border)] bg-[var(--card-bg)] px-8 py-4 font-bold text-[var(--text-primary)] transition-all hover:scale-105"
          >
            Try Again
          </button>
        </div>
      </div>
    );
  }

  if (status === 'unlinked') {
    return (
      <div className="flex min-h-[80vh] flex-col items-center justify-center text-center px-6 py-12">
        <div className="mb-8 flex h-24 w-24 items-center justify-center rounded-3xl bg-brand/10 text-brand border border-brand/20">
          <QrCode size={48} />
        </div>
        <h2 className="text-3xl font-bold text-[var(--text-primary)] tracking-tight">Board Not Activated</h2>
        <p className="mt-4 text-[var(--text-secondary)] max-w-md mx-auto leading-relaxed">
          This Smart Tolet Board is official but has not been linked to a property yet. 
          <span className="block mt-2 font-semibold text-brand">Are you the property owner?</span>
        </p>
        
        <div className="mt-12 space-y-4 w-full max-w-xs sm:max-w-md">
          <div className="rounded-2xl bg-[var(--card-bg)] border border-[var(--border)] p-6 mb-6">
            <p className="text-sm text-[var(--text-secondary)] mb-4">
              To activate this board, please login to your account and link it to your property listing.
            </p>
            <button 
              onClick={() => navigate(`/link-qr/${qrId}`)}
              className="w-full rounded-xl bg-brand py-4 font-bold text-black transition-all hover:scale-105 shadow-lg shadow-brand/20 flex items-center justify-center gap-2"
            >
              <span>Login to Activate Board</span>
            </button>
          </div>
          
          <button 
            onClick={() => navigate('/')}
            className="w-full rounded-xl border border-[var(--border)] py-4 font-bold text-[var(--text-primary)] transition-all hover:scale-105"
          >
            Explore Other Properties
          </button>
        </div>
      </div>
    );
  }

  return null;
};
